# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
                ('status', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Períodos Letivos',
                'verbose_name': 'Período Letivo',
            },
        ),
    ]
