# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 12:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodos_letivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoletivo',
            name='status',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
