# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 02:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0002_auto_20160620_2256'),
        ('disciplinas', '0001_initial'),
        ('turmas', '0002_auto_20160620_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='carga horária')),
                ('obrigatorio', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='obrigatório')),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.Disciplina', verbose_name='disciplina')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.Professor', verbose_name='professor')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.Turma', verbose_name='turma')),
            ],
        ),
    ]
