# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades_curriculares', '0002_auto_20160620_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradecurricular',
            old_name='disciplina_id',
            new_name='disciplina',
        ),
        migrations.RenameField(
            model_name='gradecurricular',
            old_name='professor_id',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='gradecurricular',
            old_name='turma_id',
            new_name='turma',
        ),
    ]
