# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='curso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='periodo_letivo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodos_letivos.PeriodoLetivo', verbose_name='Período Letivo'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='sala_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.Sala', verbose_name='Sala'),
        ),
    ]
