# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_auto_20160620_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='curso_id',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='periodo_letivo_id',
            new_name='periodo_letivo',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='sala_id',
            new_name='sala',
        ),
    ]
