# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0002_auto_20160620_2256'),
        ('modalidades', '0002_auto_20160620_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalidades.Modalidade')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.Professor')),
            ],
            options={
                'verbose_name_plural': 'Coordenadores',
            },
        ),
    ]
