# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria', verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
