# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('tempoAula', models.IntegerField(verbose_name='Tempo de Aula')),
            ],
        ),
    ]
