# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 11:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidade',
            name='tempoAula',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tempo de Aula'),
        ),
    ]
