# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eixos', '0002_auto_20160620_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificacao', models.CharField(max_length=200, verbose_name='qualificação')),
                ('eixo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eixos.Eixo')),
                ('usuario_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
