# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perguntas', '0003_auto_20160930_0736'),
        ('administradores', '0003_auto_20160924_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administradores.Administrador')),
                ('pergunta', models.ManyToManyField(to='perguntas.Pergunta')),
            ],
        ),
    ]
