# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0003_auto_20160930_0736'),
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario_Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField()),
                ('resposta', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.Pergunta')),
            ],
        ),
		
        migrations.AddField(
            model_name='questionario',
            name='pergunta',
            field=models.ManyToManyField(through='questionarios.Questionario_Pergunta', to='perguntas.Pergunta'),
        ),
        migrations.AddField(
            model_name='questionario_pergunta',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.Questionario'),
        ),
    ]
