# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0005_auto_20161022_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario_pergunta',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
