# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eixos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eixo',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='descrição'),
        ),
    ]
