# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eixos', '0002_auto_20160620_0845'),
        ('modalidades', '0002_auto_20160620_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('sigla', models.CharField(max_length=45)),
                ('eixo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eixos.Eixo')),
                ('modalidade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalidades.Modalidade')),
            ],
        ),
    ]
